### ISSUE TITLE
Moving from MAMP

### ISSUE THREAD

**Issue by yratof** [aaronbushnell/vagrant-lamp#1]
I just read your migration from MAMP to Vagrant blog post, and i'm wondering if you're able to give a few more details on the move over.

Installing vagrant & virtual box, i'm setting up a project with vagrant init, but from here, where did you go?

```
git clone git@github.com:aaronbushnell/vagrant-lamp.git
vagrant up
```

**Comment by aaronbushnell** [comment]
Hey, @yratof, here's the gist of how you'd use it. I'm going to use `mysite.dev` as an example where my document root is `/mysite/` in the `/public/` directory.

First, add a new vhost record like the one [shown here](https://github.com/aaronbushnell/vagrant-lamp/blob/master/puphpet/config.yaml#L83). You need to create a unique ID (see line #83) for your record. You also need to provide the `servername` (which is `mysite.dev`) and the `docroot` (`/var/www/mysite`).

Then, open up your hosts file in whatever editor you use (located in /etc/hosts/ in OS X) and point that domain to your Vagrant IP. For this example you'd use `192.168.35.25 mysite.dev`. 192.168.35.25 is the IP address I assigned to my Vagrant instance.

After that, run `$ vagrant reload --provision` to re-provision your Vagrantbox to find the new vhost record.

Then, try going to http://mysite.dev/ to see your new site running on the Vagrant server.

**Comment by yratof** [comment]
Awesome! Thank you for this – vagrant is such a mind blend!

**Comment by aaronbushnell** [comment]
You bet!
